export { default as Header } from './Header/Header'
export { default as GetApp } from './GetApp/GetApp'
export { default as Reviews } from './Reviews/Reviews'
export { default as Trial } from './Trial/Trial'
export { default as Footer } from './Footer/Footer'